### PR TITLE
Migration to ejs

### PR DESCRIPTION
**Pull request by flippedcoder**

### CODE REVIEW

**Comment by flippedcoder** [comment]
@UlisesGascon Here is my PR for the migration. If you want, I can go through and handle the conflicts. Just let me know what you want me to do! 😊

**Comment by UlisesGascon** [comment]
Awesome @flippedcoder! You did an amazing work. This isn't a simple change, I will review it slowly this week and I will merge it. Can you review the conflicts? I believe there are some crashes with ES6 migration from previous PRs 🤔 .

BTW This PR will count you for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) 🎉

**Comment by UlisesGascon** [comment]
Not sure why Travis is not working as expected. I will investigate it, seems like something has change in Travis but I don't believe that is related to this PR 🤔

**Comment by UlisesGascon** [comment]
I need to re-create this PR to re-run all the CI checks from zero. 😓

**Pull request closed without merging**
