### PR TITLE
"nodegoat_db_reset.js" fixed to be loaded directly in the Mongo client

### PR DESCRIPTION
**Pull request by jesusprubio**
I had problems pasting the code of the file, so I changed it to be able of loading it directly in the Mongo client. I've also updated the README to reflect the change.

### CODE REVIEW

**Comment by jesusprubio** [comment]
Hi, I've updated all the dependencies and the stuff needed to get all working again.Moreover I've implemented some little changes to improve the user deployment experience. I have some ideas to add more vulns but I think it would be better to merge this. :)

**Comment by ckarande** [comment]
@jesusprubio Thank you for PR. I am going over the changes you proposed locally before merging it. I will get back to you once reviewed.

**Comment by jesusprubio** [comment]
ok :)

**Comment by ckarande** [comment]
The changes to avoid pasting nodegoat_db_reset.js manually are great.  I have a few suggestions on data generated and other items in PR:

* A minor issue with allocations data generated, three allocation percentages should add up to 100. These are now generated as three random numbers less than 100
* In Allocations collection, user id is generated randomly (which is a good security practice) but this would break demo for [A4 vulnerability](http://nodegoat.herokuapp.com/tutorial/a4). For this vulnerability to work, the must be easy to guess and preferably sequential.
* Can the actual logic to insert data in grunt resetdb task be moved to a separate module outside of the Gruntfile.js?
* I have a doubt that your local repo was behind the OWASP/Nodegoat master when you did changes. The changes in this PR appear to have missed/overwrote some commits on [Jan 23, 2015](https://github.com/OWASP/NodeGoat/commits/master).

For ideas on additional vulnerabilities, or if you would like to discuss any of the above suggestions, feel free to join chat on [gitter](https://gitter.im/OWASP/NodeGoat)

Thanks for  you time, and contributions to improve NodeGoat :+1: Much appreciated.

**Pull request closed without merging**
