### PR TITLE
Migration to node 12

### PR DESCRIPTION
**Pull request by UlisesGascon**
### Context:
Original issue: #150 
Release Target: 1.5

- [x] Add support for Node 12
- [x] Add support for Node 10
- [x] Add support for Node 8
- [x] Update `travis.yaml` with the builds for those environments
- [x] Update the `readme.md` with the relevant info

### Changelog
- https://github.com/OWASP/NodeGoat/commit/1ff89cb6a44c0c5cd3e9d4683b63c8746fbedd93 Added Node v8 and v10 to Travis
- https://github.com/OWASP/NodeGoat/commit/1ff89cb6a44c0c5cd3e9d4683b63c8746fbedd93 Update references in doc
- https://github.com/OWASP/NodeGoat/pull/160/commits/ae31b3e7126f2a215a33d75bbdf296bba11d6750 Dockerfile upgraded to Node v12

### CODE REVIEW

**Comment by UlisesGascon** [comment]
This PR will help #149 #156 CC: @servatj

**Comment by servatj** [comment]
Indeed, Once this #160 and these #161 #156 are approved and merged I will be able to continue with #149 @UlisesGascon @ckarande 👍

**Comment by UlisesGascon** [comment]
Great catch @ckarande. :+1:

I forgot to update the `dockerfile`. Now is added to the PR 😉

**Comment by ckarande** [comment]
Awesome. Thanks @UlisesGascon 

Should we update the [apline-node version](https://github.com/OWASP/NodeGoat/pull/160/files#diff-3254677a7917c6c01f55212f86c57fbfR7)? Were you able to run the NodeGoat app in docker with these changes?

@lirantal @binarymist can you please help reviewing the docker config changes as well?

**Comment by UlisesGascon** [comment]
I am thinking that `alpine` version is fine, as we are not using any special OS Core functionality. But I will appreciate also the good advice from @lirantal @binarymist 👍 

> Alpine Linux is a distribution that was almost purpose-built for Docker images and other small, container-like uses. It clocks in at a whopping 5MB of drive space for the base operating system.

> By the time you add in the Node.js runtime requirements, this image does move up to around 50MB in space. But even at 10x the original Alpine size, it’s still 1/5 the size of the the `-slim` option.

_[Quotes source and More info](https://derickbailey.com/2017/03/09/selecting-a-node-js-image-for-docker/)_

**Comment by ckarande** [comment]
Great! Thanks for sharing the info on the `alpine` version. I am fine with leaving the version as-is as you proposed. It seem @binarymist is also fine with it. I have approved the PR. 👍 We can adjust it later if needed based on any additional feedback.

Great work 🎉

**Comment by binarymist** [comment]
My thumbs up was to give switching to alpine a go. Personally I use the alpine flavours where ever possible.

**Comment by UlisesGascon** [comment]
I will merge it now then ;-)

**Pull request merged**
