### PR TITLE
Fix - userId variable isnt set when viewing the memos page

### PR DESCRIPTION
**Pull request by lirantal**
Fixes https://github.com/OWASP/NodeGoat/issues/88

### CODE REVIEW

**Comment by lirantal** [comment]
@binarymist @ckarande I can't assign any of you as reviewers, would be nice in the future.

**Comment by ckarande** [comment]
@lirantal The changes look good and fixes the issue. Do you mind running `grunt precommit` and take care of any linting rules before I merge this PR. Thanks

**Comment by lirantal** [comment]
Sure @ckarande, I commited a fix with all out-standing jsbeautify items resulted from `grunt precommit` with the exception of small long lines linting on `test/security/profile-test.js` which I didn't touch and I'll skip for now.

**Comment by ckarande** [comment]
@lirantal This is great! Thanks

**Comment by lirantal** [comment]
My pleasure, thanks for keeping up with this great project.

**Pull request merged**
