### PR TITLE
Feature: CI with Travis

### PR DESCRIPTION
**Pull request by UlisesGascon**
***Context #144***

### Changelog
- Added Travis logic in `.travis.yml`
- Updated shebang in Mongodb seed script
- Added several tasks in package.json
- Improved configuration for mongodb url
- Improved database cleanup task in cypress

### CODE REVIEW

**Comment by UlisesGascon** [comment]
We made it!  [Green light](https://travis-ci.com/OWASP/NodeGoat/builds/121464493) in _7 min 56 sec_. 🎉 🎉 

Note: There is a lot of optimization pending :trollface:

**Comment by ckarande** [comment]
Woo hoo! Great to see the travis integrated and all green tests ending with  "The command "npm run test:ci" exited with 0." Great work, I am super excited👍. 
Once you think it is ready to merge, I will run assist in validating that tests work in local environment. Thanks!

**Comment by UlisesGascon** [comment]
Well, last changes made. It's time to review and merge @ckarande. :tada:

I will generate few issues after this merge to let other interested developers join to our refactor adventure 🌮 

If you want you can provide access to manage issues, so I can create labels and assign them to roadmaps, etc.. 😉

**Comment by ckarande** [comment]
Great work! Thank you so much for your awesome contributions. I think we can close issue#144 now? 

I will create a release with the codebase so far, so that we can start adding new enhancements. Let's collaborate on planning  what fixes to cover and order of those before the hackathon sessions. I will share some thoughts on it as a starting point. Also, I'd be happy to grant collaborator rights to you for the project. Thanks again for all your contributions.

**Comment by UlisesGascon** [comment]
Awesome!

**Pull request merged**
