### PR TITLE
Change settings docker to run everything you need to start the application

### PR DESCRIPTION
**Pull request by rrequero**
First, Great Job!!! 

I change Dockerfile and docker-compose.yml. By the way, when the people download the code and execute with docker, they don't need execute npm install, they only execute docker-compose build and docker-compose up

Thanks

### CODE REVIEW

**Comment by binarymist** [comment]
Thanks @rrequero . 
I think being specific about which directories and files are included makes a slightly slimmer image, but it also means that if additional files are added that need to run in the container, someone needs to also remember to add them to the Dockerfile. I'm not certain that being specific in this situation is better.

The `RUN npm install` "may" make sense.

I'm also wondering why you want to put the db-reset and starting of the application in the image building?
My way of thinking is that you want to reset the db and start the app when you run the container rather than when you build the image.

Thoughts?

**Comment by Pamplemousse** [comment]
Hi guys,

There are two "issues" here:
  * ```npm install``` needs to be run
  * when should we trigger the ```db-reset```

### About npm install

In #65, an ```onbuild``` image of Node is used as a base, because these ones add the current directory and files into the image and run ```npm install```. This allows all the required dependencies to be part of the image.

It seems that d1df52f in #68 changed this behaviour.

### About db-reset

> I'm also wondering why you want to put the db-reset and starting of the application in the image building? My way of thinking is that you want to reset the db and start the app when you run the container rather than when you build the image. <cite>@binarymist</cite>

As commented in https://github.com/OWASP/NodeGoat/pull/62#issuecomment-177604042, the problem with resetting the database at container start is that it can restart for legit reasons and you do not always want its data to be wiped.

**If you want to reset the data, it is better to create a new container than to restart the current one**.

Therefore, that's why in #65 the choice was made to run the reset when building the image, to ensure the database to have a clean initial state.

Commit 068041a from #68 changed this.

### Conclusion

It feels like #65 already solved all the issues that this PR is trying to solve. However, the #68 changed these behaviours.

Were there reasons for this? Did the merge revert that by accident?

**Comment by binarymist** [comment]
Thanks @Pamplemousse for your input, it's helped to clarify a number of decisions that were made before I touched the docker files. What you've said makes sense.

When I upgraded node, this was my first foray into docker, I read briefly that we probably shouldn't be using the node:onbuild and instead inherit from a non-onbuild variant, so that's where things changed.


So rather than use node:onbuild, we should probably keep being explicit about how we build.

So as mentioned, I think the `RUN npm install` may make sense. Should work if we slot it in between the current two commands in the Dockerfile?
Also having the `RUN node artifacts/db-reset.js` in the Dockerfile as it was seems to make sense. This also means that the `command` in docker-compose.yml can revert to just being an `npm start`.

Sorry for taking the long way around to update node and get to where you already were minus the node:onbuild.
If you're good with this, one of us can make the changes?

**Comment by Pamplemousse** [comment]
Yes, it sounds like using an "onbuild" image is good to start, but we can move from it and explicitly make our own one.

Adding ```RUN npm install``` will not be enough. As specified in the "node:onbuild" section of the [documentation related to the Node images](https://hub.docker.com/_/node/), you should take inspiration of the ["onbuild" Dockerfile](https://github.com/nodejs/docker-node/blob/bf93fccf8e127824cd2478f491502c7d3ad0e1aa/4.4/onbuild/Dockerfile) to see which steps needs to be taken, and in which order.

Agreed about the db-reset and the need to revert the command in the ```docker-compose.yml```.

**Comment by binarymist** [comment]
> Adding RUN npm install will not be enough.

Can you please explain why `RUN npm install` won't be enough?

> you should take inspiration of the "onbuild" Dockerfile

There is a difference between inspiration and implementation. I've looked at the "node:onbuild" section, and from what I can tell, see inline comments of your proposed change for Dockerfile:

```
RUN mkdir -p /usr/src/app // Is not required if we ADD current dir to /
WORKDIR /usr/src/app // I can't see why this is required, if we don't add the other steps that don't seem to be required.

ONBUILD COPY package.json /usr/src/app/ // Is not required as we're npm installing from the current dir which already has the package.json
ONBUILD RUN npm install // Required
ONBUILD COPY . /usr/src/app // Taken care of with the existing ADD

CMD [ "npm", "start" ] // I can't see why this is required as we already have an npm start in the docker-compose.yml, that by the looks of it, you added? Why would you want this in both files?
```

Can you please explain @Pamplemousse why you think the additional commands are required, I may be missing something?

Thanks.

**Comment by Pamplemousse** [comment]
> Adding RUN npm install will not be enough.

In fact, it would be enough and your comments are correct. However, this "naive" approach, even though perfectly working, is kind of a bad practice.

Including the app content, then installing the dependencies is highly inefficient because Docker provides a [caching system](http://thenewstack.io/understanding-the-docker-cache-for-faster-builds/) which allows to build images faster.

Adding ```RUN npm install``` after including the code means that every time the code of the app changes, this instruction will be re-triggered for building the new image (because the previous layers would have change).

However, if you build the dependencies first, then add the code, only the latter layer of the Docker image will need to be rebuilt as the one related to the ```RUN npm install``` will use the cache.

You can find a more detailed explanation here: http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js .

The Dockerfile is really how to efficiently make use of the cache mechanism:
  * create the app directory
  * make the latter instructions use this directory
  * copy ```package.json```
  * install dependencies
  * copy the app code

The ```CMD``` just provide a default behaviour and might not be useful for us.

Thanks @binarymist and hope this is clear.

**Comment by binarymist** [comment]
> Including the app content, then installing the dependencies is highly inefficient because Docker provides a caching system which allows to build images faster.
That is not what I proposed at all.
`Adding RUN npm install after including the code means that every time the code of the app changes, this instruction will be re-triggered for building the new image`
That is not what I proposed. I proposed:
`As mentioned, I think the RUN npm install may make sense. Should work if we slot it in between the current two commands in the Dockerfile?`
This means, "Adding RUN npm install **before** including the code"

> However, if you build the dependencies first, then add the code, only the latter layer of the Docker image will need to be rebuilt as the one related to the RUN npm install will use the cache.
That's exactly what I proposed.

FROM node:4.4
RUN npm install
RUN node artifacts/db-reset.js
ADD . /

**Comment by Pamplemousse** [comment]
With this snippet, where will the ```npm install``` read the dependencies from?
At this stage, the ```package.json``` is not referenced in the image yet.

**Comment by binarymist** [comment]
. ?

**Comment by Pamplemousse** [comment]
Yeah, but it's included with the ```ADD``` instruction, coming after the ```RUN``` one.
So it is not yet in the image for ```npm install``` as the instructions are executed sequentially.

**Comment by binarymist** [comment]
My machine is packed for flights, so can't play, but I would have thought that if the commands knew that '.' was the current dir, then the `npm install` would know that the `package.json` was also in '.'

**Comment by binarymist** [comment]
Created revised PR #73.
Adding the db-reset in the Dockerfile doesn't work, I think the reason is that the mongo container isn't running at that point, so I'm not sure how the db-reset can be run from the Dockerfile. Any suggestions @Pamplemousse?

**Comment by Pamplemousse** [comment]
Hi @binarymist, sorry for the long wait.

As far as I can tell, its seems in fact this has never been working (\*ashamed of my testing\*: guess the mongo container was already present when I did it)...

I am having a look at what could be done to solve the problem. Maybe cleaning the database seeding process is a track to look at.

I created the issue #76, seems to be a better place to continue the discussion.

This can be closed IMO as @binarymist 's #73 is the best thing we can have so far.

**Comment by binarymist** [comment]
Thanks @Pamplemousse. I'll have a look at some options when I can make some room on my desk.

**Comment by ckarande** [comment]
Thanks @rrequero @Pamplemousse and @binarymist . Closing this PR. #73 is merged.

**Pull request closed without merging**
