### PR TITLE
Add nodemon

### PR DESCRIPTION
**Pull request by servatj**
Adds nodemon as npm script related to the #156 issue

- [X] Remove Forever dependency as is not in use.
- [X]  Add Nodemon as dependency
- [X] Add task dev to the package.json that allow us to reload the server on changes, see
is not in use, let's move to Nodemon as npm script
- [X]  Check that the npm tasks are working as expected
- [X]  Update the readme.md with the extra relevant info (if needed)

### CODE REVIEW

**Comment by servatj** [comment]
@ckarande Thanks for having me! You're totally right I misplaced the nodemon file in test folder, and also i removed the -watch option in package.json so nodemon gets the settings from the config properly.

**Comment by ckarande** [comment]
@servatj Thanks for the changes. Looks good to me and we are all set to merge this PR. 🎉

**Comment by UlisesGascon** [comment]
Cool @ckarande @servatj  :-) I just updated the PR base branch to `OWASP:release-1.5` as expected

**Comment by ckarande** [comment]
Awesome! @UlisesGascon Excellent work organizing the PRs with the right release branch. Please feel free to merge the PR when you get a chance.

**Comment by UlisesGascon** [comment]
Thanks @ckarande !! 👍

**Pull request merged**
