### PR TITLE
allows to test mongodb uri via env vars

### LINKED ISSUE #173: Unable to pass env vars to set mongodb uri
We use NodeGoat to test some of our code and we programmatically pass in mongodb uri via `MONGODB_URI` env var.  This worked just fine until #147 was merged.  The changed in https://github.com/OWASP/NodeGoat/pull/147/files#diff-5ad5fa7320dd1d0531493bee405d385b made the 2 env vars useless.

### PR DESCRIPTION
**Pull request by bizob2828**
This restores the ability to pass in `MONGOLAB_URI` and `MONGODB_URI` as env vars to set the mongo db uri.

Fixes #173

### CODE REVIEW

**Comment by ckarande** [comment]
@bizob2828 Thanks for the PR. LGTM

**Comment by UlisesGascon** [comment]
Thanks @bizob2828 this PR seems good to me. I will move the target branch to `version-1.5`. I will merge it tomorrow, so this PR will count you for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) 🎉

**Comment by bizob2828** [comment]
ok thanks @UlisesGascon.  When will 1.5 be released? I'm currently just using the fork in our test harness but would love to restore using this main repo

**Comment by UlisesGascon** [comment]
@bizob2828 not sure yet about the date. There are many issues and PRs on going. I will ping you back when we have an estimation 👍

**Pull request merged**
