### PR TITLE
Adding NPM configuration for pointing to global registry.

### PR DESCRIPTION
**Pull request by IAmAnubhavSaini**
### Note:

JSHint is already screaming about long lines. I have not touched that file. This PR has no code changes, just adding a configuration file.

### CODE REVIEW

**Comment by ckarande** [comment]
@IAmAnubhavSaini Thanks for the PR. Could you please provide some more context / need for explicitly pointing to the npm global registry. Isn't it the default registry if not set?

**Comment by IAmAnubhavSaini** [comment]
That's true.

### Context

On some `corporate` systems, NPM registry points to private one; updating that breaks local tooling. 

### Is it really needed though?

It removes annoyance. Two aliases can do the same job, but that's needed to be done for every time terminal is relaunched.

### and

It affects NPM setting on the directory level. There is no harm in having a file that sets registry for the directory/repository.

**Comment by binarymist** [comment]
Is nodegoat being used within a corporate environment?

**Comment by ckarande** [comment]
@IAmAnubhavSaini Thanks for the PR. In case nodegoat is used within corporate  environment, I would prefer it to use the corporate npm registry by default if one exists. Was there a specific issue that led to your comment `On some corporate systems, NPM registry points to private one; updating that breaks local tooling.`?

**Comment by ckarande** [comment]
Closing the PR. Please feel free to reopen it with details requested. thanks

**Pull request closed without merging**
