### PR TITLE
fix: Fix problem of blank alert on the sign up page

### PR DESCRIPTION
**Pull request by Ahnteve**
I fixed the empty alert in sign up page!

signup.html
```
...
<div class="row">
  <div class="col-lg-12">
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p>{{userNameError}}{{firstNameError}}{{lastNameError}}{{passwordError}}{{verifyError}}{{emailError}}</p>
    </div>
  </div>
</div>
...
```
```
...
{% if userNameError || firstNameError || lastNameError || passwordError || verifyError || emailError %}
  <div class="row">
    <div class="col-lg-12">
      <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <p>{{userNameError}}{{firstNameError}}{{lastNameError}}{{passwordError}}{{verifyError}}{{emailError}}</p>
      </div>
    </div>
  </div>
{% endif %}
...
```

### CODE REVIEW

**Comment by lirantal** [comment]
@Ahnteve is it possible to get a PR that only makes the necessary change and not change the formatting of the code across all these files?

**Comment by lirantal** [comment]
And of course thank you for opening a PR and submitting a fix! 🤗

**Comment by Ahnteve** [comment]
!!! OK! Hold on a minute, please!!

**Comment by Ahnteve** [comment]
@lirantal I sent PR again. Please check PR! 😉

**Comment by lirantal** [comment]
Looks great, thanks @Ahnteve! 💪

**Comment by ckarande** [comment]
Great work @Ahnteve  @lirantal. Thanks !

**Pull request merged**
